### PR TITLE
Fix several issues introduced by VS2017 and add automatic testing.

### PR DESCRIPTION
**Pull request by AndreasSchoenle**
I have not tested how these changes affect VS2015 and before. It seems that the runtime has changed in some aspects (i.e. for ACCESS_VIOLATION SEH exceptions we are now landing in the sigsegv signal handler)  and I have tried to address these issues here.

Would be thankful if this could be tested in a VS2015 environment. In VS2017 the current CrashRpt unit tests do not run properly even on [master](../) so I have not checked against those.

### CODE REVIEW

**Comment by jowr** [comment]
Hi, I do not have access to VS2015, but 2013 Professional reports those errors.

```Shell
Error	1	error C1083: Cannot open include file: 'minidumpapiset.h': No such file or directory (D:\TMP\CrashRpt2\processing\crashrptprobe\CrashDescReader.cpp)	D:\TMP\CrashRpt2\thirdparty\dbghelp\include\dbghelp.h	3837
Error	2	error C1083: Cannot open include file: 'minidumpapiset.h': No such file or directory (D:\TMP\CrashRpt2\processing\crashrptprobe\CrashRptProbe.cpp)	D:\TMP\CrashRpt2\thirdparty\dbghelp\include\dbghelp.h	3837
Error	3	error C1083: Cannot open include file: 'minidumpapiset.h': No such file or directory (D:\TMP\CrashRpt2\processing\crashrptprobe\MinidumpReader.cpp)	D:\TMP\CrashRpt2\thirdparty\dbghelp\include\dbghelp.h	3837
Error	4	error LNK1117: syntax error in option 'DEBUG:FULL'	D:\TMP\CrashRpt2.win.build\reporting\crashrpt\LINK
Error	5	error C1083: Cannot open include file: 'minidumpapiset.h': No such file or directory (D:\TMP\CrashRpt2\reporting\crashrpt\Utility.cpp)	D:\TMP\CrashRpt2\thirdparty\dbghelp\include\dbghelp.h	3837
Error	6	error LNK1117: syntax error in option 'DEBUG:FULL'	D:\TMP\CrashRpt2.win.build\tests\LINK
```

**Comment by jowr** [comment]
Sorry for the noise, I compiled the master branch and not your "fix-minor-issues" branch. Your does not compile at all, but I guess that is due to the new C++ features.

**Comment by jowr** [comment]
Here is the output from VS2013 (32bit) for your branch: 
```Shell
cmake ..\CrashRpt2 -G"Visual Studio 12 2013"
cmake --build . --target Tests --config Release
```

```Shell
"D:\TMP\CrashRpt2.2013.win.build\tests\Tests.vcxproj" (default target) (1) ->
"D:\TMP\CrashRpt2.2013.win.build\processing\crashrptprobe\CrashRptProbe.vcxproj" (default target) (4) ->
"D:\TMP\CrashRpt2.2013.win.build\thirdparty\minizip\minizip.vcxproj" (default target) (5) ->
"D:\TMP\CrashRpt2.2013.win.build\thirdparty\zlib\zlib.vcxproj" (default target) (6) ->
(ClCompile target) ->
  D:\TMP\CrashRpt2\thirdparty\zlib\gzread.c(317): warning C4245: '=' : conversion from 'int' to 'unsigned int', signed/unsigned mismatch [D:\TMP\CrashRpt2.2013.win.build\thirdparty\zlib\zlib.vcxproj]


"D:\TMP\CrashRpt2.2013.win.build\tests\Tests.vcxproj" (default target) (1) ->
"D:\TMP\CrashRpt2.2013.win.build\processing\crashrptprobe\CrashRptProbe.vcxproj" (default target) (4) ->
"D:\TMP\CrashRpt2.2013.win.build\thirdparty\minizip\minizip.vcxproj" (default target) (5) ->
  D:\TMP\CrashRpt2\thirdparty\minizip\zip.c(1248): warning C4057: '=' : 'const unsigned long *' differs in indirection to slightly different base types from 'const z_crc_t *' [D:\TMP\CrashRpt2.2013.win.build\thirdparty\minizip\minizip.vcxp roj]


"D:\TMP\CrashRpt2.2013.win.build\tests\Tests.vcxproj" (default target) (1) ->
"D:\TMP\CrashRpt2.2013.win.build\reporting\crashrpt\CrashRpt.vcxproj" (default target) (3) ->
(ClCompile target) ->
  D:\TMP\CrashRpt2\include\CrashRpt.h(1637): error C3646: 'noexcept' : unknown override specifier (D:\TMP\CrashRpt2\reporting\crashrpt\CrashRpt.cpp) [D:\TMP\CrashRpt2.2013.win.build\reporting\crashrpt\CrashRpt.vcxproj]
  D:\TMP\CrashRpt2\include\CrashRpt.h(1637): error C3646: 'noexcept' : unknown override specifier (D:\TMP\CrashRpt2\reporting\crashrpt\CrashHandler.cpp) [D:\TMP\CrashRpt2.2013.win.build\reporting\crashrpt\CrashRpt.vcxproj]
  D:\TMP\CrashRpt2\include\CrashRpt.h(1637): error C2072: 'crEmulateCrash' : initialization of a function (D:\TMP\CrashRpt2\reporting\crashrpt\CrashRpt.cpp) [D:\TMP\CrashRpt2.2013.win.build\reporting\crashrpt\CrashRpt.vcxproj]
  D:\TMP\CrashRpt2\include\CrashRpt.h(1637): error C2072: 'crEmulateCrash' : initialization of a function (D:\TMP\CrashRpt2\reporting\crashrpt\CrashHandler.cpp) [D:\TMP\CrashRpt2.2013.win.build\reporting\crashrpt\CrashRpt.vcxproj]
  D:\TMP\CrashRpt2\include\CrashRpt.h(1637): error C2440: 'initializing' : cannot convert from 'bool' to 'int (unsigned int)' (D:\TMP\CrashRpt2\reporting\crashrpt\CrashRpt.cpp) [D:\TMP\CrashRpt2.2013.win.build\reporting\crashrpt\CrashRpt.v cxproj]
  D:\TMP\CrashRpt2\include\CrashRpt.h(1637): error C2440: 'initializing' : cannot convert from 'bool' to 'int (unsigned int)' (D:\TMP\CrashRpt2\reporting\crashrpt\CrashHandler.cpp) [D:\TMP\CrashRpt2.2013.win.build\reporting\crashrpt\CrashR pt.vcxproj]
  D:\TMP\CrashRpt2\reporting\crashrpt\CrashRpt.cpp(886): error C3646: 'noexcept' : unknown override specifier [D:\TMP\CrashRpt2.2013.win.build\reporting\crashrpt\CrashRpt.vcxproj]
  D:\TMP\CrashRpt2\reporting\crashrpt\CrashRpt.cpp(887): error C2448: 'crEmulateCrash' : function-style initializer appears to be a function definition [D:\TMP\CrashRpt2.2013.win.build\reporting\crashrpt\CrashRpt.vcxproj]


"D:\TMP\CrashRpt2.2013.win.build\tests\Tests.vcxproj" (default target) (1) ->
"D:\TMP\CrashRpt2.2013.win.build\processing\crashrptprobe\CrashRptProbe.vcxproj" (default target) (4) ->
  D:\TMP\CrashRpt2\thirdparty\dbghelp\include\dbghelp.h(3837): fatal error C1083: Cannot open include file: 'minidumpapiset.h': No such file or directory (D:\TMP\CrashRpt2\processing\crashrptprobe\CrashRptProbe.cpp) [D:\TMP\CrashRpt2.2013. win.build\processing\crashrptprobe\CrashRptProbe.vcxproj]
  D:\TMP\CrashRpt2\thirdparty\dbghelp\include\dbghelp.h(3837): fatal error C1083: Cannot open include file: 'minidumpapiset.h': No such file or directory (D:\TMP\CrashRpt2\processing\crashrptprobe\CrashDescReader.cpp) [D:\TMP\CrashRpt2.201 3.win.build\processing\crashrptprobe\CrashRptProbe.vcxproj]
  D:\TMP\CrashRpt2\thirdparty\dbghelp\include\dbghelp.h(3837): fatal error C1083: Cannot open include file: 'minidumpapiset.h': No such file or directory (D:\TMP\CrashRpt2\processing\crashrptprobe\MinidumpReader.cpp) [D:\TMP\CrashRpt2.2013 .win.build\processing\crashrptprobe\CrashRptProbe.vcxproj]
  D:\TMP\CrashRpt2\thirdparty\dbghelp\include\dbghelp.h(3837): fatal error C1083: Cannot open include file: 'minidumpapiset.h': No such file or directory (D:\TMP\CrashRpt2\reporting\crashrpt\Utility.cpp) [D:\TMP\CrashRpt2.2013.win.build\pr ocessing\crashrptprobe\CrashRptProbe.vcxproj]
```

**Comment by AndreasSchoenle** [comment]
I have fixed the noexcept() error which is not supported by VS2013 (_MSC_VER must be >= 1900) so the old throw(...) is reproduced for older versions. BTW I think both are unnecessary.

About the missing header: It is part of the windows SDK. It seems like the dbghelp DLL part of this CrashRpt version is incompatible with your currently installed WindowsSDK or for some reason you are using the wrong SDK include directories. The file is at: `C:\Program Files (x86)\Windows Kits\10\Include\10.0.16299.0\um` on my computer. 

Installing a newer SDK should fix the issue. Also, the missing header should be a problem for both master and the fix-minor-issues branch.

**Comment by jowr** [comment]
Thanks - I am not sure, if it is that easy. 

Everything compiles for VS2017, which probably means that I have all the dependencies in place. 

Maybe the SDK is not compatible with VS2013?

There is also a typo in your code, it should be `#if _MSC_VER >= 1900` and not `#ifdef _MSC_VER >= 1900`.

**Comment by jowr** [comment]
36c1795537c82390e2bab4a2b0807320681c6d26 successfully fixed the linker flag issue

**Comment by jowr** [comment]
There seems to be a problem with VS2013, but VS2015 should work: https://blogs.msdn.microsoft.com/chuckw/2015/07/30/windows-10-sdk-rtm/

**Comment by AndreasSchoenle** [comment]
@jowr Please try again. I have blindly edited the CMake files so they use the installed windows SDK for VS versions before 2015. 
To be quite honest, the rationale behind delivering as a third party library is not entirely clear to me as dbghelp.dll itself has multiple (not only header) dependencies. So it is not obvious on which systems putting it side-by-side will actually make CrashRpt work.

**Comment by AndreasSchoenle** [comment]
@jowr Builds on VS2013 via appveyor. @QbProg in your opinion, how should dbghelp be dealt with?

**Comment by jowr** [comment]
Builds for me too, some tests fail though:
```Shell
 Time elapsed: 9.42 sec.
 Test count: 67
 Tests passed: 20
 Tests failed: 47
```

**Comment by jowr** [comment]
Thanks a lot, everything looks fine! Any comments @QbProg ?

**Comment by vnl** [comment]
Is this getting merged at all?

**Comment by QbProg** [comment]
thanks for the code guys! 
re-tested in VS2017.8 32bit and 64bit, everything's fine.

**Pull request merged**
