### PR TITLE
Install symbol files, too.

### PR DESCRIPTION
**Pull request by AndreasSchoenle**

### CODE REVIEW

**Comment by QbProg** [comment]
like it, but what if we add an Option?

**Comment by AndreasSchoenle** [comment]
Are you still maintaining this? I have updated the PR to make PDB installation optional.

**Comment by jowr** [comment]
Hey @AndreasSchoenle - it looks like I have write access to this repo. Are you still interested in merging your PR? Would it make sense to create an organisation/group on GitHub to maintain this library?

**Comment by AndreasSchoenle** [comment]
Hey @jowr - sure, merging the PR would be great. It would actually put QbProg/master to exactly the commit we are using in production. 
As to an organisation/group: It would certainly be good to have an actively maintained repository where someone reviews and handles PRs and Issues timely enough for people to actually contribute.

As long as you have write access to this repo and are willing to do this, it could also be here. Any alternative is fine with me, too and I will try to support it.

**Pull request merged**
